### ISSUE TITLE
edge_vision_soc.v(768): ERROR: instantiating unknown module 'dma' (VERI-1063)

### ISSUE THREAD

**Issue by johnny2231** [Efinix-Inc/evsoc#1]
Hi,

after I generate all the ips for the project: T120F324_1280_720
and try to compile / synthesis it, i got that error message.

I noticed in ip/dma, there is **no dma.v generated.**

I tried to look into the details of what is happening by right clicking IP:dma, click configure, and generate, I got a lot of error messages, the first error message is this:

ERROR : Give the json configuration file as first arguement. 
Traceback (most recent call last): 
File "C:\Efinity\2021.2\python38\lib\shutil.py", line 781, in move 
os.rename(src, real_dst) 
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\efinix\\evsoc-main\\T120F324_1280_720\\outflow\\EfxDMA.v' -> 'C:\\efinix\\evsoc-main\\T120F324_1280_720\\ip\\dma\\source\\EfxDMA.v' 

I aware of this:
_Important: Open-source Java 64-bit runtime environment is required for generating the DMA Controller core in the IP Manager_
And I have made sure that the PATH env has the java.

But the dma.v can't be generated.

May I know how to solve this issue?
(I am using Efinity on Windows 10)

**Comment by maris77** [comment]
Hi @johnny2231 ,

looks like you have a problem with resource installation.
since only dma are not able to be generate, we can try to check with java installation first.

can check installed version with cmd "java -version" and you will see printed msg as below,

_{
java version "1.8.0_301"
Java(TM) SE Runtime Environment (build 1.8.0_301-b09)
Java HotSpot(TM) Client VM (build 25.301-b09, mixed mode, sharing)
}_

please help to provide us your outputs for further investigation.

thanks,
Aris

**Comment by johnny2231** [comment]
Hi @maris77 , sorry for being late in getting back to you.

The java version is:

{
java version "1.8.0_333"
Java(TM) SE Runtime Environment (build 1.8.0_333-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.333-b02, mixed mode)
}


Just to clarify, the original issue signature is this, after generate the ips, when I tried to compile I will face this issue below:
![image](https://user-images.githubusercontent.com/55950816/186161353-79935e8f-cbb9-4344-a150-7586e9ee89e3.png)

Then I tried to debug and came across the issue faced on the first comment.
Which I right-click the ip:dma > configure > generate, and I got these errors:
![image](https://user-images.githubusercontent.com/55950816/186165899-3b58e99e-5d53-4285-b8b9-bbe920eb4a69.png)

The other IPs can be generated without issue, just dma cannot be generated.

Hope you can help, thanks!

**Comment by johnny2231** [comment]
Moving this example project folder to Desktop. the issue is resolved.
Most probably due to folder name with space instead of _

However, in Efinity IDE v2022.1.226, the Sapphire and DMA IPs cannot be generated because these IPs cannot be upgraded.
A message will pop up and requires user to remove the these 2 IPs and generate the new instance to use the updated IP. 

Tried to remove the IPs and import again, an error message will appears on console:
_VLNV not exists in IP Catalog, on path C:/Users/User/Desktop/doi_Documents/Master/master project/efinix/project examples/evsoc-main/T120F324_1280_720/ip/SapphireSoc/settings.json_

Since this issue is resolved on Efinity IDE v2021.2.323 with the patch, this issue will be closed as solved.
